# This is a basic workflow to help you get started with Actions

name: Pre-process files

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a  job called "build"
  convert_docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[noaction]')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: install wkhtml
      run: sudo apt-get install wkhtmltopdf xvfb
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Create directory
      run: "[[ -d templates ]] || mkdir templates "

    # Runs a single command using the runners shell
    - name: Create temp directory
      run: "[[ -d temp ]] || mkdir temp "

    # Runs a set of commands using the runners shell
    - name: Run docker for HTML 
      uses: docker://pandoc/latex:2.9
      with:
          args: "template-README.md --standalone -t html5                          -o temp/README.html --metadata pagetitle=README "
    - name: Convert HTML to PDF
      run: "/usr/bin/xvfb-run /usr/bin/wkhtmltopdf temp/README.html templates/README.pdf"
      
    - name: Run docker for Docx
      uses: docker://pandoc/latex:2.9
      with:
          args: "template-README.md --standalone -t docx                           -o templates/README.docx "
    - name: Run docker for latex
      uses: docker://pandoc/latex:2.9
      with:
          args: "template-README.md --standalone -t latex --template=default.latex -o templates/README.tex"
    - name: Add files
      run: |
        git add templates/README.*
    - name: push files
      uses: EndBug/add-and-commit@v4
      with: 
        message: '[noaction] Generated derived files'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload
      uses: actions/upload-artifact@master
      with:
          name: templates
          path: templates
